apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.headNode.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.headNode.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.headNode.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.headNode.name }}
        {{- include "vllm.labels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.additionalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.headNode.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.headNode.name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.headNode.ports.ray }}
            - containerPort: {{ .Values.headNode.ports.vllm }}
          resources:
            {{- toYaml .Values.headNode.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          command:
            {{- toYaml .Values.headNode.command | nindent 12 }}
          {{- with .Values.additionalEnvVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}