# head-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vllm-head-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.head.type }}
  selector:
    app: {{ .Values.headNode.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.head.port }}
      targetPort: {{ .Values.headNode.ports.ray }}

---
# vllm-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.vllm.type }}
  selector:
    app: {{ .Values.headNode.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.vllm.port }}
      targetPort: {{ .Values.headNode.ports.vllm }}
      {{- if eq .Values.service.vllm.type "NodePort" }}
      nodePort: {{ .Values.service.vllm.nodePort }}
      {{- end }}