{{- if .Values.workerNodes.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vllm-worker
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: vllm-worker
  template:
    metadata:
      labels:
        app: vllm-worker
        {{- include "vllm.labels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.additionalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      # Node selection
      {{- with .Values.workerNodes.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workerNodes.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: vllm-worker
          image: "{{ .Values.image.workerRepository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.workerNodes.ports.vllm }}
          resources:
            {{- toYaml .Values.workerNodes.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          command:
            {{- toYaml .Values.workerNodes.command | nindent 12 }}
          {{- with .Values.additionalEnvVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
{{- end }}